project:
  type: website

website:
  title: "Nhat Tran"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css

    toc: true
