project:
  type: website
  resources:
    - image/photo1.JPG
    - image/photo2.JPG
    - image/photo3.JPG
    - image/photo4.JPG
    - image/photo5.JPG

website:
  title: "Nhat Tran"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Academics
        menu:
          - text: Relevant Coursework
            href: coursework.qmd
          - text: Python Notebooks
            href: pynotes.qmd
      - text: Projects
        href: projects.qmd
      - text: Certifications
        href: certifications.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



