website:
  title: "Nhat Tran"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Academics
        menu:
          - text: Relevant Coursework
            href: coursework.qmd
          - text: Python Notebooks
            href: pynotes.qmd
      - text: Projects
        href: projects.qmd
      - text: Certifications
        href: certifications.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd

    right:
      - icon: github
        href: https://github.com/nhattran309
        aria-label: GitHub

      - icon: linkedin
        href: https://www.linkedin.com/in/nhat-tran-30999/
        aria-label: LinkedIn
